//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopBackgroundChangerUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://photography.nationalgeographic.com/photography/photo-of-the-day/")]
        public string NG_Default {
            get {
                return ((string)(this["NG_Default"]));
            }
            set {
                this["NG_Default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("animals/")]
        public string NG_Animals {
            get {
                return ((string)(this["NG_Animals"]));
            }
            set {
                this["NG_Animals"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("adventure-exploration/")]
        public string NG_Adventure {
            get {
                return ((string)(this["NG_Adventure"]));
            }
            set {
                this["NG_Adventure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("history/")]
        public string NG_History {
            get {
                return ((string)(this["NG_History"]));
            }
            set {
                this["NG_History"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("black-white/")]
        public string NG_BlackAndWhite {
            get {
                return ((string)(this["NG_BlackAndWhite"]));
            }
            set {
                this["NG_BlackAndWhite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("landscapes/")]
        public string NG_Landscapes {
            get {
                return ((string)(this["NG_Landscapes"]));
            }
            set {
                this["NG_Landscapes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nature-weather/")]
        public string NG_Nature {
            get {
                return ((string)(this["NG_Nature"]));
            }
            set {
                this["NG_Nature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("people-culture/")]
        public string NG_People {
            get {
                return ((string)(this["NG_People"]));
            }
            set {
                this["NG_People"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("science-space/")]
        public string NG_Science {
            get {
                return ((string)(this["NG_Science"]));
            }
            set {
                this["NG_Science"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("travel/")]
        public string NG_Travel {
            get {
                return ((string)(this["NG_Travel"]));
            }
            set {
                this["NG_Travel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("underwater/")]
        public string NG_Underwater {
            get {
                return ((string)(this["NG_Underwater"]));
            }
            set {
                this["NG_Underwater"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://desktopchanger.codeplex.com/")]
        public string ApplicationWebsite {
            get {
                return ((string)(this["ApplicationWebsite"]));
            }
            set {
                this["ApplicationWebsite"] = value;
            }
        }
    }
}
